### ISSUE TITLE
Add new field `handler` in `Chain`

### ISSUE THREAD

**Issue by tolak** [Phala-Network/index-contract#49]
Currently, we hardcode the `handler` contract address, we need to add the `handler` in `Chain` and uploaded it along with the graph provided by off-chain. The `handler` in index/graph/Chain should be defined as `Vec<u8>`, it represents a smart contract address in EVM chains and a MultiLocation encoded bytes in Substrate chains.

**Comment by tenheadedlion** [comment]
certainly, what is the handler used for?

**Comment by tolak** [comment]
@tenheadedlion For EVM chain, initialise contract instance
https://github.com/Phala-Network/index-contract/blob/d1c83e0e69972a937342f7a87abe2cdc3437388f/contracts/index_executor/src/claimer.rs#L180-L182
https://github.com/Phala-Network/index-contract/blob/d1c83e0e69972a937342f7a87abe2cdc3437388f/contracts/index_executor/src/claimer.rs#L112-L114
