### ISSUE TITLE
Remove ink storage layout

### ISSUE THREAD

**Issue by tolak** [Phala-Network/index-contract#5]
Currently, ink forces customized types to implement storage layout whenever being stored in contract storage,  it's too hard to add layout definition to all of the ready-to-save types. We could consider introducing a wrapper to isolate the customized types from contract storage. For example,

```rust
#[derive(scale::Encode, scale::Decode)]
struct Customized {
    foo: String,
    bar: u128,
},
```
And in ink contract,

```rust
#[derive(
   scale::Encode, scale::Decode, SpreadLayout, PackedLayout,
)]
#[cfg_attr(feature = "std", derive(scale_info::TypeInfo, StorageLayout,))]
struct CustomizedWrapper {
    /// Encoded Customized structure
    customized: Vec<u8>,
},
```

**Comment by kvinwang** [comment]
I meant the Wrapper by something static-typed like:
```rust
#[derive(Encode, Decode)]
struct Scale<T>(T);

impl<T> SpreadLayout for Scale<T> where T: Encode + Decode {
...
}
impl<T> PackedLayout for Scale<T> where T: Encode + Decode {
...
}
impl<T> Deref for Scale<T> {
    type Target = T;
    fn deref(&self) -> &T {
        &self.0
    }
}
```

And use it in this way:
```rust
#[ink::storage]
struct MyContract {
    foo: Scale<Customized>,
}
```
where `Customized` is an external type implementing Encode + Decode.

Not sure whether it would work.

**Comment by tolak** [comment]
Sounds great, we will consider wrapping our custom like this way if Ink4.0 not act as we expected
